services:
  app:
    build: .
    user: app
    command: coverage run --source=django_scrubber manage.py test
    volumes:
      - .:/app
    environment:
      IPYTHONDIR: /app/.ipython
      HISTFILE: /app/.bash_history
    restart: "no"
