services:
  app:
    build:
      context: .
    user: app
    entrypoint: /app/manage.py
    command: coverage run --source=django_scrubber manage.py test
    volumes:
      - .:/app:cached
    environment:
      IPYTHONDIR: /app/.ipython
      HISTFILE: /app/.bash_history
    restart: "no"
